site_name: Curate Documentation
site_url: https://penwern.github.io/curate-documentation/
theme:
  name: 'material'
  logo: /curate-documentation/assets/Penwern Logo Large.png
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode with high contrast
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tracking
extra_css:
  - style.css
extra:
  homepage: https://www.penwern.co.uk
plugins:
  - redirects:
      redirect_maps:
        'documentation.md': 'index.markdown'
markdown_extensions:
  - toc:
      permalink: true