name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust if your primary branch differs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false  # This is important for the peaceiris/actions-gh-pages action

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material  # Ensure all dependencies are listed

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_COMMITTER_NAME: your-github-username  # Replace with your GitHub username
          GIT_COMMITTER_EMAIL: your-email@example.com  # Replace with your email
          GIT_AUTHOR_NAME: your-github-username  # Replace with your GitHub username
          GIT_AUTHOR_EMAIL: your-email@example.com  # Replace with your email
