name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust if your primary branch differs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false  # This is important for the peaceiris/actions-gh-pages action

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material  # Ensure all dependencies are listed

      - name: Custom Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdocs build --clean
          git checkout -b gh-pages
          git add -f site
          git -c user.name='GitHub Actions' -c user.email='actions@github.com' commit -m 'Deploy MkDocs Site'
          git push --force ${{ secrets.GITHUB_TOKEN }}@github.com/penwern/curate-documentation.git gh-pages:gh-pages

