name: Deploy MkDocs to Soteria and Curate GitHub Pages

on:
  push:
    branches:
      - main # Adjust if your primary branch differs

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material # Ensure all dependencies are listed
      
      - name: Build and Deploy Curate Documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdocs build --clean
          cd site
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m 'Deploy Curate MkDocs Site'
          git remote add origin https://x-access-token:${GITHUB_TOKEN}@github.com/penwern/curate-documentation.git
          git push -f origin HEAD:gh-pages
      
      - name: Generate Soteria+ Documentation
        run: |
          mkdir soteria-plus-docs
          cp -R docs/* soteria-plus-docs/
          find soteria-plus-docs/ -type f -name '*.md' -exec sed -i 's/Curate/Soteria+/g' {} +
          # Add more sed commands to replace other Curate-specific terms with Soteria+ equivalents
      
      - name: Build and Deploy Soteria+ Documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdocs build --clean --config-file mkdocs-soteria-plus.yml --site-dir soteria-plus-site
          cd soteria-plus-site
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m 'Deploy Soteria+ MkDocs Site'
          git remote add origin https://x-access-token:${GITHUB_TOKEN}@github.com/penwern/soteria-plus-documentation.git
          git push -f origin HEAD:gh-pages
